name: Build and Push MongoDB Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed for pushing to GHCR

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mongo-dev:${{ env.SHORT_SHA }}


      - name: Clone app-config repo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://github.com/ynon24/app-config.git
          cd app-config
          echo "${{ env.SHORT_SHA }}" > mongodb-version.txt
          git add mongodb-version.txt
          git commit -m "Update MongoDB image tag to ${{ env.SHORT_SHA }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ynon24/app-config.git HEAD:main


